#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           6
bspc config focused_border_color '#F5A97F'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &
feh --bg-scale ~/wallpapers/xp.jpg
polybar &
xrdb -merge ~/.Xresources

setxkbmap -option -option grp:shifts_toggle -option ctrl:nocaps pl,ua

amixer -c 0 set Master 90%
