#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           12
bspc config focused_border_color '#c6a0f6'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &
feh --bg-scale ~/Wallpapers/dark-cat.png
polybar &

amixer -c 0 set Master 90%
